const TOPICS={
priority:{name:'Проезд перекрёстков',icon:'▣'},
signals:{name:'Сигналы светофора и регулировщика',icon:'◉'},
signs:{name:'Дорожные знаки',icon:'△'},
pedestrians:{name:'Пешеходы',icon:'♙'},
manoeuvres:{name:'Маневрирование',icon:'↔'},
stopping:{name:'Остановка и стоянка',icon:'P'},
speed:{name:'Скорость и дистанция',icon:'◷'},
special:{name:'Специальные сигналы',icon:'✦'},
wording:{name:'Формулировки вопросов',icon:'≡'}
};

const Q=[
{t:'priority',s:'yield',q:'Вы подъезжаете к нерегулируемому перекрёстку. Перед вами установлен знак «Уступить дорогу», а справа приближается автомобиль по пересекаемой дороге. Что необходимо определить прежде всего?',a:['Находится ли автомобиль справа','Как знак приоритета определяет очередность движения','Кто движется быстрее','Кто первым приблизился к перекрёстку'],c:1,r:'Сначала учитываются действующие средства организации движения. Дополнительные правила применяются после этого.',e:'Знак приоритета уже задаёт основу очередности. Ошибка — автоматически начинать решение с правила помехи справа.',m:'Слишком рано применяете помеху справа'},
{t:'priority',s:'city',q:'Вы поворачиваете налево на разрешающий сигнал светофора. Встречный автомобиль движется прямо и также имеет разрешающий сигнал. Как действовать?',a:['Закончить поворот первым','Уступить встречному автомобилю','Проехать одновременно','Остановиться и ждать красного сигнала'],c:1,r:'При конфликте траекторий левый поворот требует учёта встречного движения, которому разрешено движение прямо.',e:'Разрешающий сигнал позволяет движение, но не создаёт безусловного преимущества перед встречной конфликтующей траекторией.',m:'Считаете зелёный сигнал безусловным преимуществом'},
{t:'priority',s:'residential',q:'На нерегулируемом перекрёстке равнозначных дорог другой автомобиль находится справа от вас. Знаков приоритета и регулирования нет. Что определяет очередность?',a:['Размер автомобилей','Кто раньше начал торможение','Необходимость уступить транспортному средству справа','Кто движется прямо'],c:2,r:'На равнозначном нерегулируемом перекрёстке после проверки отсутствия иных средств приоритета применяется правило помехи справа.',e:'Здесь правило справа уместно именно потому, что более приоритетных средств регулирования нет.',m:'Неправильно определяете момент применения помехи справа'},
{t:'signals',s:'city',q:'Светофор работает в режиме жёлтого мигающего сигнала. Как выбирать очередность проезда перекрёстка?',a:['Как на обычном регулируемом перекрёстке','Всегда пропускать тех, кто едет прямо','Рассматривать перекрёсток как нерегулируемый и учитывать знаки приоритета','Обязательно останавливаться независимо от условий'],c:2,r:'Жёлтый мигающий сигнал предупреждает об опасности, но не задаёт обычную очередность как рабочие разрешающие и запрещающие сигналы.',e:'Нужно перейти от логики обычного светофорного регулирования к анализу знаков и приоритета.',m:'Неправильно интерпретируете режим светофора'},
{t:'signals',s:'city',q:'Регулировщик подаёт сигнал, который не совпадает с работающим светофором. Чем должен руководствоваться водитель?',a:['Светофором','Сигналом регулировщика','Знаком главной дороги','Тем указанием, которое удобнее'],c:1,r:'При непосредственном регулировании движения сигналы регулировщика являются определяющими.',e:'Нельзя выбирать более удобное указание: при регулировщике именно его сигналы становятся основными.',m:'Не знаете иерархию регулирования'},
{t:'signals',s:'city',q:'Включился разрешающий сигнал, но за перекрёстком затор и вы не сможете освободить его, не перекрыв поперечное движение. Как действовать?',a:['Въехать, потому что сигнал разрешающий','Въехать с аварийной сигнализацией','Не въезжать до возможности освободить перекрёсток','Въехать, если сзади сигналят'],c:2,r:'Разрешающий сигнал не означает право блокировать перекрёсток при заторе за ним.',e:'Нужно оценивать возможность закончить проезд, а не только цвет сигнала.',m:'Игнорируете ситуацию за перекрёстком'},
{t:'signs',s:'residential',q:'На знакомом участке появилась временная схема движения, отличающаяся от обычной. Как действовать?',a:['Ехать по памяти','Ориентироваться на актуальные знаки и временную организацию движения','Игнорировать временные знаки','Следовать только навигатору'],c:1,r:'Временная организация движения вводится именно для изменения обычного порядка на участке.',e:'Знакомство с дорогой не даёт права игнорировать актуальные средства организации движения.',m:'Игнорируете временную организацию движения'},
{t:'signs',s:'city',q:'Навигатор предлагает повернуть, но установленный знак запрещает этот манёвр. Какое решение правильное?',a:['Следовать навигатору','Руководствоваться знаком и изменить маршрут','Остановиться в полосе','Повернуть, если рядом нет инспектора'],c:1,r:'Навигационное приложение не заменяет действующие средства организации дорожного движения.',e:'Навигатор строит маршрут, а дорожный знак определяет допустимые действия на дороге.',m:'Слишком доверяете навигатору'},
{t:'signs',s:'city',q:'Знак разрешает движение в определённом направлении из вашей полосы, но для манёвра пришлось бы пересечь действующую сплошную линию разметки. Как анализировать ситуацию?',a:['Раз знак разрешает направление, разметку можно игнорировать','Учитывать одновременно знак, разметку и фактическую возможность манёвра','Всегда важнее только разметка','Манёвр допустим при отсутствии встречных машин'],c:1,r:'Средства организации движения рассматриваются совместно; разрешённое направление не отменяет другого действующего ограничения.',e:'Сложность такой задачи — в сочетании нескольких условий, а не в распознавании одного символа.',m:'Не объединяете условия задачи'},
{t:'pedestrians',s:'pedestrian',q:'При повороте направо пешеход уже пересекает проезжую часть по траектории, которую вы собираетесь занять. Что необходимо учитывать?',a:['Только сигнал вашего светофора','Только скорость пешехода','Конфликт траекторий и необходимость не создавать опасность','Только наличие автомобилей сзади'],c:2,r:'При повороте водитель оценивает пешеходов, чья траектория пересекается с направлением движения автомобиля.',e:'Даже разрешённое движение автомобиля не отменяет анализа пешеходной траектории.',m:'Недостаточно учитываете пешеходов при повороте'},
{t:'pedestrians',s:'pedestrian',q:'Пешеход стоит у края проезжей части возле перехода и явно готовится начать движение. Какой подход безопаснее?',a:['Учитывать только его текущее положение','Прогнозировать возможное начало движения и заранее иметь запас реакции','Продолжать без изменения режима до выхода на дорогу','Подать сигнал и ехать дальше'],c:1,r:'Безопасное управление требует прогнозировать развитие ситуации, а не реагировать только после появления опасности.',e:'Важен не только факт, где пешеход сейчас, но и где он может оказаться через секунду.',m:'Реагируете поздно вместо прогнозирования'},
{t:'pedestrians',s:'pedestrian',q:'Перед переходом обзор справа частично закрыт стоящим автомобилем. Как это влияет на ваши действия?',a:['Никак, если пешехода не видно','Следует учитывать возможное появление пешехода из закрытой зоны','Нужно быстрее проехать участок','Достаточно звукового сигнала'],c:1,r:'Ограниченная обзорность увеличивает неопределённость и требует заранее учитывать скрытую опасность.',e:'Сложный вопрос проверяет способность увидеть риск, которого пока физически не видно.',m:'Не учитываете скрытую опасность'},
{t:'manoeuvres',s:'lane',q:'Вы собираетесь перестроиться в соседнюю полосу, где уже движется автомобиль без изменения направления. Как действовать?',a:['Автомобиль в полосе должен уступить','Перестраивающийся водитель должен обеспечить безопасный манёвр','Преимущество у того, кто первым включил поворотник','Преимущество у более быстрого автомобиля'],c:1,r:'Перестроение не создаёт преимущества; водитель должен убедиться, что манёвр безопасен.',e:'Указатель поворота сообщает о намерении, но не заставляет соседа уступить.',m:'Считаете поворотник источником преимущества'},
{t:'manoeuvres',s:'lane',q:'Вы включили указатель поворота заранее. Даёт ли это право сразу начать перестроение?',a:['Да, если прошло несколько секунд','Да, если соседний автомобиль немного сзади','Нет, сначала нужно убедиться в безопасности','Да, если вы движетесь быстрее'],c:2,r:'Сигнал поворота предупреждает других участников, но не заменяет проверку безопасности и приоритета.',e:'Предупреждение о манёвре и право выполнить манёвр — разные вещи.',m:'Переоцениваете значение указателя поворота'},
{t:'manoeuvres',s:'lane',q:'Автомобиль в соседней полосе находится немного позади, но быстро сокращает дистанцию. Что нужно учитывать перед перестроением?',a:['Только его текущее положение','Скорость сближения и возможность безопасно завершить манёвр','Только свой указатель поворота','Только ограничение скорости'],c:1,r:'Манёвр оценивается по динамике движения, а не только по мгновенному положению автомобилей.',e:'Автомобиль может быть позади сейчас, но через секунду оказаться рядом.',m:'Не учитываете скорость сближения'},
{t:'manoeuvres',s:'lane',q:'Вы пропустили нужный поворот и уже находитесь в полосе, из которой повернуть нельзя. Что безопаснее?',a:['Резко перестроиться','Остановиться в полосе','Продолжить движение и выбрать следующий безопасный маршрут','Сдать назад'],c:2,r:'Ошибка маршрута не является основанием для опасного манёвра.',e:'Потерять минуту безопаснее, чем резко исправлять маршрут.',m:'Исправляете маршрут рискованным манёвром'},
{t:'stopping',s:'residential',q:'Вы нашли свободное место рядом с перекрёстком. Что необходимо проверить до остановки?',a:['Только достаточно ли места','Ограничения, обзорность и влияние на других участников','Стоят ли рядом другие автомобили','Удобно ли потом выехать'],c:1,r:'Свободное место само по себе не означает, что остановка разрешена и безопасна.',e:'Нужно оценивать не только физическое место, но и ограничения и обзорность.',m:'Считаете свободное место автоматически разрешённым'},
{t:'stopping',s:'residential',q:'Несколько автомобилей уже припаркованы там, где вы сомневаетесь в разрешённости остановки. Что это означает?',a:['Остановка разрешена, если машин много','Остановка разрешена, если они стоят давно','Их наличие не заменяет проверку правил и знаков','Достаточно включить аварийную сигнализацию'],c:2,r:'Поведение других водителей не является нормативным основанием для вашего решения.',e:'Нельзя автоматически повторять действия окружающих.',m:'Копируете действия других водителей'},
{t:'speed',s:'rain',q:'После начала сильного дождя ухудшилась видимость и сцепление с дорогой. Какое изменение поведения наиболее обоснованно?',a:['Сохранить прежнюю скорость, если она в пределах лимита','Снизить скорость и увеличить запас дистанции','Сократить дистанцию, чтобы видеть машину впереди','Ускориться, чтобы быстрее проехать дождь'],c:1,r:'Ухудшение сцепления и видимости увеличивает требуемый запас времени и расстояния.',e:'Разрешённая скорость — верхняя граница, а не гарантия безопасности в любых условиях.',m:'Не адаптируете скорость к условиям'},
{t:'speed',s:'lane',q:'Разрешённая скорость выше той, при которой вы можете уверенно остановиться в пределах видимого пространства. Как выбирать скорость?',a:['Всегда двигаться с максимально разрешённой','Выбрать меньшую скорость с учётом видимости и условий','Ориентироваться только на поток','Ускориться для быстрого прохождения участка'],c:1,r:'Максимально разрешённая скорость — предел, а фактические условия могут требовать меньшей.',e:'Нужно различать «разрешено до» и «безопасно сейчас».',m:'Путаете разрешённую и безопасную скорость'},
{t:'speed',s:'rain',q:'Почему хорошая тормозная система не устраняет риск при позднем обнаружении препятствия?',a:['Автомобиль проходит расстояние ещё во время реакции водителя','Тормоза работают только после остановки','Тормозной путь не зависит от скорости','Обзорность важна только ночью'],c:0,r:'До начала торможения проходит время восприятия и реакции, в течение которого автомобиль продолжает движение.',e:'Полный остановочный путь начинается раньше фактического срабатывания тормозов.',m:'Недооцениваете путь за время реакции'},
{t:'special',s:'city',q:'Позади приближается специальный автомобиль со специальными световыми и звуковыми сигналами. Какой общий принцип определяет действия водителя?',a:['Продолжать без изменений','Безопасно создать условия для его беспрепятственного проезда','Резко остановиться в любой полосе','Ускориться выше ограничения'],c:1,r:'Предоставление возможности для проезда специального транспорта должно выполняться безопасно и предсказуемо.',e:'Резкое действие может создать новую опасность; важен безопасный способ освободить путь.',m:'Выбираете резкое действие вместо безопасного'},
{t:'special',s:'city',q:'Можно ли считать проблесковый маячок любого цвета одинаковым основанием для автоматического преимущества?',a:['Да, любой маячок даёт одинаковое преимущество','Нет, значение зависит от типа сигнала и правил его применения','Да, если автомобиль движется быстро','Да, если маячок хорошо виден'],c:1,r:'Разные специальные световые сигналы имеют различное назначение и правовой эффект.',e:'Нельзя обобщать значение всех маячков.',m:'Обобщаете значение специальных сигналов'},
{t:'wording',s:'none',q:'В вопросе спрашивается: «Обязан ли водитель…». Какой способ чтения снижает риск ошибки?',a:['Искать самый безопасно звучащий вариант','Определить, требуется ли именно обязательное действие, а не допустимое','Выбрать самый длинный ответ','Вспомнить похожую картинку'],c:1,r:'Слова «обязан», «может», «разрешается» и «запрещается» задают разные условия ответа.',e:'Часто ошибка возникает не из-за незнания правила, а из-за подмены смысла формулировки.',m:'Не различаете обязательное и допустимое действие'},
{t:'wording',s:'none',q:'Два ответа почти одинаковы, но один содержит уточнение «только при…». Как лучше сравнить варианты?',a:['Выбрать более короткий','Сопоставить каждое условие ответа с точной формулировкой задачи','Выбрать знакомый вариант','Ориентироваться только на начало предложения'],c:1,r:'Одно дополнительное условие может полностью изменить корректность ответа.',e:'Экзаменационные ловушки часто строятся на небольшом, но юридически значимом уточнении.',m:'Пропускаете значимые уточнения'},
{t:'wording',s:'none',q:'Почему после ошибки полезно сформулировать правило своими словами, а не просто запомнить правильную букву?',a:['Это проверяет понимание принципа','Это полностью заменяет изучение правил','Это гарантирует отсутствие ошибок','Это полезно только инструктору'],c:0,r:'Пересказ своими словами помогает проверить, усвоен ли принцип, который можно перенести на новую ситуацию.',e:'Запомненная буква работает только в знакомом вопросе; понимание работает при изменении условий.',m:'Запоминаете ответ вместо принципа'}
];

const KB=[
{keys:['помех','справа','равнознач'],topic:'priority',title:'Помеха справа',text:'Правило справа нельзя применять автоматически. Сначала проверь регулирование, знаки приоритета и равнозначность дорог. Только когда более конкретные средства не задают очередность, оцени положение участника справа.'},
{keys:['светофор','зелён','желт','регулиров'],topic:'signals',title:'Светофор и регулирование',text:'Разрешающий сигнал позволяет движение, но не отменяет конфликтующие обязанности: пешеходов, встречные траектории при повороте и невозможность блокировать перекрёсток. При регулировщике сначала учитываются его сигналы.'},
{keys:['перестро','полос','поворотник','маневр'],topic:'manoeuvres',title:'Перестроение',text:'Указатель поворота предупреждает о намерении, но не создаёт преимущества. Перед боковым перемещением оцени соседнюю полосу, слепую зону и скорость сближения.'},
{keys:['пешеход','переход'],topic:'pedestrians',title:'Пешеходы',text:'При поворотах и ограниченной обзорности оцени не только текущее положение пешехода, но и развитие ситуации. Главный вопрос — пересекаются ли ваши траектории и есть ли запас для безопасной реакции.'},
{keys:['скорост','дистанц','дожд','видим','тормоз'],topic:'speed',title:'Скорость и дистанция',text:'Ограничение скорости задаёт верхний предел. Реальная безопасная скорость и дистанция зависят от видимости, покрытия, времени реакции и возможности остановиться в контролируемом пространстве.'},
{keys:['останов','стоян','парков'],topic:'stopping',title:'Остановка и стоянка',text:'Свободное место и наличие других припаркованных автомобилей не доказывают разрешённость. Сначала проверь ограничения, затем обзорность и влияние автомобиля на других участников.'},
{keys:['знак','размет','навигатор'],topic:'signs',title:'Знаки и разметка',text:'Не решай задачу по одному объекту. Учитывай действующие знаки, разметку, сигналы и фактическую дорожную обстановку совместно. Навигатор не заменяет требования дороги.'},
{keys:['спец','маяч','сирен'],topic:'special',title:'Специальный транспорт',text:'Специальные сигналы имеют разное назначение. Если требуется предоставить путь, делай это предсказуемо и безопасно, не создавая опасного резкого манёвра.'}
];

const KEY='pdd_ai_v2_state';
const DEFAULT={version:2,onboard:false,cat:'B',goal:14,explain:'simple',dailyGoal:10,answered:0,correct:0,streak:0,lastDay:'',todayCount:0,todayDate:'',topics:{},mistakes:[],bookmarks:[],history:[],reviews:[],chat:[]};
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...DEFAULT,...x,topics:x.topics||{},mistakes:x.mistakes||[],bookmarks:x.bookmarks||[],history:x.history||[],reviews:x.reviews||[],chat:x.chat||[]}}catch(e){return {...DEFAULT}}}
let S=loadState(),session=null,timer=null,lastAnswer=null,lastResult=null,topicFilter='all';
const $=id=>document.getElementById(id);

function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function stat(t){if(!S.topics[t])S.topics[t]={n:0,c:0,w:0};return S.topics[t]}
function score(t){const x=stat(t);return x.n?Math.max(5,Math.round(x.c/x.n*100)):50}
function accuracy(){return S.answered?Math.round(S.correct/S.answered*100):0}
function readiness(){const a=Object.keys(TOPICS).map(score),avg=a.reduce((x,y)=>x+y,0)/a.length,vol=Math.min(1,S.answered/100);return Math.min(99,Math.round(avg*.74+vol*25))}
function weakTopic(){return Object.keys(TOPICS).sort((a,b)=>score(a)-score(b))[0]}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function formatTime(s){s=Math.max(0,Math.round(s||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function masterIndex(q){return Q.indexOf(q)}
function resetToday(){const d=new Date().toISOString().slice(0,10);if(S.todayDate!==d){S.todayDate=d;S.todayCount=0;save()}}function markActivity(){const d=new Date().toISOString().slice(0,10);if(S.lastDay===d)return;const p=new Date(Date.now()-86400000).toISOString().slice(0,10);S.streak=S.lastDay===p?S.streak+1:1;S.lastDay=d;save()}
function dueReviews(){const now=Date.now();return S.reviews.filter(x=>x.due<=now).sort((a,b)=>a.due-b.due)}
function scheduleReview(idx,wrong=true){let r=S.reviews.find(x=>x.idx===idx);if(!r){r={idx,level:0,due:Date.now()};S.reviews.push(r)}if(wrong){r.level=0;r.due=Date.now()+10*60*1000}else{r.level=Math.min(4,(r.level||0)+1);const gaps=[10*60*1000,864e5,3*864e5,7*864e5,14*864e5];r.due=Date.now()+gaps[r.level]}save()}

function init(){resetToday();if(!S.onboard)$('onboard').classList.add('active');if(!S.chat.length){S.chat=[{role:'agent',text:'Привет. Я AI‑агент ПДД. Могу объяснить правило простыми словами, разобрать последнюю ошибку или подобрать тренировку по твоему слабому месту.'}];save()}render()}
function finishOnboard(){S.cat=$('onCat').value;S.goal=+$('onGoal').value;S.onboard=true;save();$('onboard').classList.remove('active');render()}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render();scrollTo(0,0)}
function render(){const r=readiness(),w=weakTopic(),a=accuracy();$('homePct').textContent=r+'%';$('homeRing').style.background='conic-gradient(var(--green) '+r*3.6+'deg,#153149 0)';$('continueTopic').textContent='Тема: '+TOPICS[w].name;$('continueMeta').textContent=Math.min(S.todayCount,S.dailyGoal)+' из '+S.dailyGoal;$('statAnswered').textContent=S.answered;$('statAccuracy').textContent=a+'%';$('statStreak').textContent=S.streak;$('statErrors').textContent=S.mistakes.length;$('topicsCat').textContent=S.cat;$('profileCat').value=S.cat;$('explainMode').value=S.explain;$('dailyGoal').value=String(S.dailyGoal);$('categoryStrip').innerHTML=['B','A','C','D'].map(c=>'<button class="category '+(S.cat===c?'active':'')+'" onclick="setCategory(\''+c+'\')"><b>'+c+'</b><small>'+({B:'Легковые',A:'Мото',C:'Грузовые',D:'Автобусы'}[c])+'</small></button>').join('');renderDue();renderTopics();renderAnalytics();renderAgent()}
function renderDue(){const d=dueReviews();$('dueTitle').textContent=d.length?d.length+' вопрос'+(d.length===1?'':'а')+' ждут повторения':'Сегодня всё повторено';$('dueText').textContent=d.length?'Вернись к ошибкам, пока правило не закрепилось.':'Ошибки будут возвращаться через интервалы, чтобы знания не забывались.';$('dueBtn').disabled=!d.length}
function setCategory(v){S.cat=v;save();render();toast('Категория '+v+' выбрана')}
function setExplainMode(v){S.explain=v;save();toast('Режим объяснений сохранён')}
function setDailyGoal(v){S.dailyGoal=+v;save();render();toast('Дневная цель обновлена')}
function setTopicFilter(v,btn){topicFilter=v;document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderTopics()}
function renderTopics(){let keys=Object.keys(TOPICS);if(topicFilter==='weak')keys=keys.filter(k=>stat(k).n&&score(k)<75);if(topicFilter==='new')keys=keys.filter(k=>!stat(k).n);$('topicList').innerHTML=keys.length?keys.map(k=>{const x=stat(k),s=score(k),v=TOPICS[k];return '<button class="surface topic-item" onclick="startTopic(\''+k+'\')"><div class="topic-line"><div><b>'+v.icon+' '+v.name+'</b><br><small>'+x.n+' решено • '+x.w+' ошибок</small></div><strong>'+s+'%</strong></div><div class="bar"><i style="width:'+s+'%"></i></div></button>'}).join(''):'<div class="surface topic-item"><small>Здесь пока пусто.</small></div>'}
function renderAnalytics(){const r=readiness();$('analyticsPct').textContent=r+'%';$('analyticsRing').style.background='conic-gradient(var(--green) '+r*3.6+'deg,#153149 0)';$('metricAnswered').textContent=S.answered;$('metricCorrect').textContent=S.correct;$('metricExams').textContent=S.history.length;const keys=Object.keys(TOPICS).sort((a,b)=>score(a)-score(b)).slice(0,5);$('weakList').innerHTML=keys.map((k,i)=>{const s=score(k),color=i<2?'#ff6268':i<4?'#ff9f43':'#38e09d';return '<div class="weak-row"><span>'+TOPICS[k].icon+' '+TOPICS[k].name+'</span><div class="weakbar"><i style="width:'+s+'%;background:'+color+'"></i></div><b style="color:'+color+'">'+s+'%</b></div>'}).join('');$('examHistory').innerHTML=S.history.length?S.history.slice().reverse().slice(0,8).map(h=>'<div class="surface history"><div><b class="'+(h.pass?'c-green':'c-red')+'">'+(h.pass?'Сдан':'Не сдан')+'</b><br><small>'+new Date(h.date).toLocaleString('ru-RU')+'</small></div><div><b>'+h.errors+' ош.</b><br><small>'+formatTime(h.sec)+'</small></div></div>').join(''):'<div class="surface history"><small>Попыток пока нет.</small></div>'}

function pick(pool,n){const out=[];shuffle(pool).forEach(q=>{if(!out.includes(q))out.push(q)});return out.slice(0,Math.min(n,out.length))}
function startPractice(){startSession('practice',pick(Q,12))}
function startSmart(){const w=weakTopic();startSession('smart',pick(Q.filter(q=>q.t===w).concat(Q.filter(q=>q.t!==w)),10))}
function startWeak(){const ids=[...new Set(S.mistakes.slice().reverse().map(x=>x.idx))];let p=ids.map(i=>Q[i]).filter(Boolean);if(p.length<8)p=p.concat(Q.filter(q=>q.t===weakTopic()));startSession('weak',pick(p,10))}
function startSaved(){const p=S.bookmarks.map(i=>Q[i]).filter(Boolean);if(!p.length)return toast('В избранном пока нет вопросов');startSession('saved',pick(p,10))}
function startDue(){const p=dueReviews().map(r=>Q[r.idx]).filter(Boolean);if(!p.length)return toast('Повторений пока нет');startSession('review',p.slice(0,10))}
function startTopic(t){startSession('topic',pick(Q.filter(q=>q.t===t),10))}
function startExam(){startSession('exam',pick(Q,10))}
function startSession(mode,questions){if(!questions.length)return toast('Для этого режима пока нет вопросов');session={mode,questions,index:0,answers:new Array(questions.length).fill(null),errors:0,correct:0,start:Date.now(),deadline:mode==='exam'?Date.now()+900000:null,finished:false};$('questionScreen').classList.add('active');if(mode==='exam'){clearInterval(timer);timer=setInterval(tickExam,500)}renderQuestion()}
function tickExam(){if(!session||session.mode!=='exam')return;const left=Math.ceil((session.deadline-Date.now())/1000);if(left<=0){finishExam('time');return}renderMeta()}
function renderMeta(){const total=session.questions.length;$('questionCounter').textContent='Вопрос '+(session.index+1)+' из '+total;if(session.mode==='exam')$('questionTimer').textContent=formatTime(Math.ceil((session.deadline-Date.now())/1000));else $('questionTimer').textContent=({practice:'Тренировка',smart:'Научи меня',weak:'Слабые',saved:'Избранное',review:'Повторение',topic:'Обучение'}[session.mode]||'Практика')}
function sceneLabel(s){return {yield:'Нерегулируемый перекрёсток',city:'Городской перекрёсток',residential:'Жилая улица',pedestrian:'Пешеходный переход',lane:'Многополосная дорога',rain:'Дождь и ограниченная видимость',none:'Текстовый вопрос'}[s]||'Дорожная ситуация'}
function renderQuestion(){const q=session.questions[session.index],ans=session.answers[session.index],exam=session.mode==='exam';renderMeta();$('questionTopic').textContent=TOPICS[q.t].name;const mi=masterIndex(q);$('bookmark').textContent=S.bookmarks.includes(mi)?'♥':'♡';const img=(window.SCENE_IMAGES||{})[q.s];$('scene').classList.toggle('has-photo',!!img);$('scene').style.backgroundImage=img?'linear-gradient(180deg,rgba(0,0,0,.02),rgba(0,0,0,.30)),url('+img+')':'';$('scene').innerHTML='<span class="scene-label">'+sceneLabel(q.s)+'</span>';$('scene').style.display=q.s==='none'?'none':'block';$('questionText').textContent=q.q;$('answers').innerHTML=q.a.map((a,i)=>{let cls='answer',mark='';if(ans!==null&&!exam){if(i===q.c){cls+=' correct';mark='✓'}else if(i===ans){cls+=' wrong';mark='×'}}return '<button class="'+cls+'" '+(ans!==null?'disabled':'')+' onclick="answerQuestion('+i+')"><span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+a+'</span><span>'+mark+'</span></button>'}).join('');$('prevQuestion').disabled=session.index===0||exam;$('nextQuestion').disabled=ans===null;$('nextQuestion').textContent=session.index===session.questions.length-1?'Завершить':'Далее ›'}
function answerQuestion(i){if(session.answers[session.index]!==null)return;const q=session.questions[session.index],mi=masterIndex(q),ok=i===q.c,st=stat(q.t);session.answers[session.index]=i;markActivity();S.answered++;S.todayCount++;st.n++;if(ok){S.correct++;session.correct++;st.c++;if(session.mode==='review')scheduleReview(mi,false)}else{session.errors++;st.w++;S.mistakes.push({idx:mi,topic:q.t,m:q.m,date:new Date().toISOString()});if(S.mistakes.length>200)S.mistakes=S.mistakes.slice(-200);scheduleReview(mi,true)}save();lastAnswer={q,choice:i,correct:ok,idx:mi};if(session.mode==='exam'){if(!ok&&session.errors>=2){finishExam('second');return}if(session.index===session.questions.length-1){finishExam('complete');return}session.index++;renderQuestion();return}renderQuestion();setTimeout(openExplanation,120)}
function previousQuestion(){if(session&&session.index>0){session.index--;renderQuestion()}}
function nextQuestion(){if(!session)return;if(session.answers[session.index]===null)return toast('Сначала выбери ответ');if(session.index===session.questions.length-1){session.mode==='exam'?finishExam('complete'):finishTraining();return}session.index++;renderQuestion()}
function attemptCloseQuestion(){if(session&&session.mode==='exam'&&session.answers.some(x=>x!==null)){if(!confirm('Завершить экзамен досрочно? Попытка будет сохранена как незавершённая.'))return;finishExam('abandoned');return}closeQuestion()}
function closeQuestion(){clearInterval(timer);$('questionScreen').classList.remove('active');session=null;render()}
function toggleBookmark(){if(!session)return;const idx=masterIndex(session.questions[session.index]),p=S.bookmarks.indexOf(idx);if(p>=0)S.bookmarks.splice(p,1);else S.bookmarks.push(idx);save();renderQuestion();toast(p>=0?'Удалено из избранного':'Добавлено в избранное')}

function openExplanation(){const x=lastAnswer;if(!x)return;$('questionScreen').classList.remove('active');$('explainScreen').classList.add('active');$('answerVerdict').className='verdict'+(x.correct?'':' bad');$('answerVerdict').innerHTML='<b class="'+(x.correct?'c-green':'c-red')+'">'+(x.correct?'✓ Правильный ответ':'× Ошибка')+'</b><br>'+String.fromCharCode(65+x.q.c)+'. '+x.q.a[x.q.c];let text=x.q.e;if(!x.correct)text+='<br><br><b>Почему выбранный вариант не подходит:</b> '+wrongReason(x.q,x.choice);if(S.explain==='brief')text=x.q.e;if(S.explain==='deep')text+='<br><br><b>Алгоритм:</b> выдели факты → определи главное правило → проверь конфликт траекторий → оцени безопасность.';$('explanationText').innerHTML=text;$('ruleBox').innerHTML='<b>Ключевой принцип</b><br>'+x.q.r;$('miniAIReply').textContent=''}
function wrongReason(q,c){return c===q.c?'Выбран правильный вариант.':'Вариант «'+q.a[c]+'» не учитывает главное условие. Типичная ошибка: '+q.m+'.'}
function closeExplanation(){$('explainScreen').classList.remove('active');$('questionScreen').classList.add('active')}
function continueAfterExplanation(){$('explainScreen').classList.remove('active');$('questionScreen').classList.add('active');if(session.index===session.questions.length-1)finishTraining();else{session.index++;renderQuestion()}}
function miniAI(type){if(!lastAnswer)return;const q=lastAnswer.q;let t='';if(type==='simple')t='Решай в порядке: что регулирует ситуацию → кто имеет приоритет → пересекаются ли траектории → безопасно ли действие. Здесь главное: '+q.r;if(type==='why')t=wrongReason(q,lastAnswer.choice);if(type==='remember')t='Запомни не букву ответа, а триггер ошибки: '+q.m+'. При следующем похожем вопросе сначала проверь именно это.';if(type==='similar')t='Я добавлю похожую ситуацию в повторение. В ней изменится одно условие, чтобы проверить понимание, а не память.';$('miniAIReply').textContent=t}

function finishTraining(){const answered=session.answers.filter(x=>x!==null).length;lastResult={pass:true,title:'Тренировка завершена',subtitle:'Правильно '+session.correct+' из '+answered+'. Следующая адаптивная сессия учтёт эти ответы.',errors:session.errors,answered,sec:Math.round((Date.now()-session.start)/1000),wrong:session.answers.map((x,i)=>x!==null&&x!==session.questions[i].c?masterIndex(session.questions[i]):null).filter(x=>x!==null)};clearInterval(timer);$('questionScreen').classList.remove('active');showResult();session=null;render()}
function finishExam(reason){if(!session||session.finished)return;session.finished=true;clearInterval(timer);const answered=session.answers.filter(x=>x!==null).length,left=Math.max(0,Math.ceil((session.deadline-Date.now())/1000)),sec=900-left,pass=reason==='complete'&&answered===10&&session.errors<=1;const rec={date:new Date().toISOString(),pass,errors:session.errors,answered,sec,reason};S.history.push(rec);if(S.history.length>50)S.history=S.history.slice(-50);save();lastResult={pass,title:pass?'Экзамен сдан':'Экзамен не сдан',subtitle:pass?'Допущено не более одной ошибки. Отличная попытка.':reason==='second'?'Вторая ошибка — экзамен автоматически завершён.':reason==='time'?'Время истекло.':reason==='abandoned'?'Попытка завершена досрочно.':'Попытка завершена.',errors:session.errors,answered,sec,wrong:session.answers.map((x,i)=>x!==null&&x!==session.questions[i].c?masterIndex(session.questions[i]):null).filter(x=>x!==null)};$('questionScreen').classList.remove('active');showResult();session=null;render()}
function showResult(){const r=lastResult;$('resultIcon').textContent=r.pass?'✓':'×';$('resultIcon').className='result-icon'+(r.pass?'':' fail');$('resultTitle').textContent=r.title;$('resultSubtitle').textContent=r.subtitle;$('resultMetrics').innerHTML='<div class="surface"><b>'+r.answered+'</b><small>ответов</small></div><div class="surface"><b>'+r.errors+'</b><small>ошибок</small></div><div class="surface"><b>'+formatTime(r.sec)+'</b><small>время</small></div>';$('resultReview').innerHTML=r.wrong.length?'<div class="surface result-review"><b>Что повторить:</b><br>'+[...new Set(r.wrong.map(i=>TOPICS[Q[i].t].name))].join(' • ')+'</div>':'<div class="surface result-review"><b class="c-green">Ошибок нет.</b> Закрепи результат на новых формулировках.</div>';$('resultReviewBtn').style.display=r.wrong.length?'block':'none';$('resultScreen').classList.add('active')}
function closeResult(){$('resultScreen').classList.remove('active');showPage('home')}
function reviewLastResult(){if(!lastResult||!lastResult.wrong.length)return;const p=[...new Set(lastResult.wrong)].map(i=>Q[i]);$('resultScreen').classList.remove('active');startSession('review',p)}
function resetProgress(){if(confirm('Удалить локальный прогресс, историю и чат?')){localStorage.removeItem(KEY);location.reload()}}

function renderAgent(){const w=weakTopic();$('agentFocus').textContent='Слабее всего: '+TOPICS[w].name+' — '+score(w)+'%';$('agentFocusText').textContent=dueReviews().length?'Есть '+dueReviews().length+' вопрос(а) для повторения. Можешь попросить меня объяснить их.':'Спроси правило или попроси составить тренировку.';$('chat').innerHTML=S.chat.slice(-30).map((m,i)=>'<div class="msg '+m.role+'">'+escapeHtml(m.text)+(m.topic?'<div class="actions"><button onclick="startTopic(\''+m.topic+'\')">Тренировать тему</button></div>':'')+'</div>').join('');setTimeout(()=>{$('chat').scrollTop=$('chat').scrollHeight},0)}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function askPreset(t){$('agentInput').value=t;sendAgent()}
function agentKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendAgent()}}
async function sendAgent(){const input=$('agentInput'),q=input.value.trim();if(!q)return;input.value='';S.chat.push({role:'user',text:q});const answer=await agentAnswer(q);S.chat.push({role:'agent',text:answer.text,topic:answer.topic||null});if(S.chat.length>60)S.chat=S.chat.slice(-60);save();renderAgent()}
async function agentAnswer(q){const low=q.toLowerCase();if(/последн.*ошиб|ошиб.*последн/.test(low)){const m=S.mistakes.at(-1);if(!m)return{text:'У тебя пока нет сохранённых ошибок. Пройди несколько вопросов — после этого я смогу разобрать конкретную ситуацию.'};const x=Q[m.idx];return{text:'Последняя ошибка была в теме «'+TOPICS[x.t].name+'». '+x.e+' Ключевой принцип: '+x.r+' Типичная причина: '+x.m+'.',topic:x.t}}if(/слаб|где.*ошиб|что.*повтор/.test(low)){const w=weakTopic();return{text:'Сейчас самая слабая тема — «'+TOPICS[w].name+'»: '+score(w)+'%. Я бы начал с короткой тренировки по этой теме, а затем повторил вопросы, на которых уже были ошибки.',topic:w}}if(/подготов|план|экзамен/.test(low)){const r=readiness(),d=S.goal||14,w=weakTopic();return{text:'Текущая оценка готовности — '+r+'%. На ближайший цикл: 1) ежедневно '+S.dailyGoal+' вопросов; 2) сначала «'+TOPICS[w].name+'»; 3) закрывать все вопросы из умного повторения; 4) после этого сдавать полный экзамен. Цель в профиле: '+(d?d+' дней':'без даты')+'.',topic:w}}let best=null,bestScore=0;for(const k of KB){let sc=0;k.keys.forEach(x=>{if(low.includes(x))sc+=2});const words=low.split(/[^а-яёa-z0-9]+/).filter(x=>x.length>3);words.forEach(w=>{if(k.text.toLowerCase().includes(w)||k.title.toLowerCase().includes(w))sc++});if(sc>bestScore){bestScore=sc;best=k}}if(best&&bestScore>0)return{text:best.title+': '+best.text+' Если хочешь, открой тренировку — я подберу вопросы именно по этой теме.',topic:best.topic};const words=low.split(/[^а-яёa-z0-9]+/).filter(x=>x.length>3);let ranked=Q.map((x,i)=>({x,i,s:words.reduce((n,w)=>n+(x.q.toLowerCase().includes(w)?2:0)+(x.e.toLowerCase().includes(w)?1:0)+(x.r.toLowerCase().includes(w)?1:0),0)})).sort((a,b)=>b.s-a.s);if(ranked[0]&&ranked[0].s>1){const x=ranked[0].x;return{text:'Ближе всего твой вопрос относится к теме «'+TOPICS[x.t].name+'». '+x.r+' '+x.e,topic:x.t}}return{text:'Я пока не хочу придумывать норму, которой нет в моей проверенной локальной базе. Переформулируй вопрос через конкретную ситуацию — кто куда едет, какой знак или сигнал действует. Тогда я смогу разобрать логику точнее.'}}
init();